2022-07-15 11:47:40 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-07-15 11:47:40 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration ui_lovelace_minimalist which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-07-15 11:47:40 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration birthdays which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-07-15 11:47:40 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration afvalwijzer which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-07-15 11:47:40 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration browser_mod which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-07-15 11:47:41 WARNING (MainThread) [homeassistant.config] Package homeassistant contains invalid customize
2022-07-15 11:47:47 ERROR (MainThread) [homeassistant.setup] Error during setup of component browser_mod
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/config/custom_components/browser_mod/__init__.py", line 39, in async_setup
    for d in config[DOMAIN].get(CONFIG_DEVICES, {}):
KeyError: 'browser_mod'
2022-07-15 11:47:48 ERROR (MainThread) [custom_components.ui_lovelace_minimalist.load_plugins] HACS Frontend repo "button-card" is already installed, Remove it or disable include custom cards
2022-07-15 11:47:48 ERROR (MainThread) [custom_components.ui_lovelace_minimalist.load_plugins] HACS Frontend repo "light-entity-card" is already installed, Remove it or disable include custom cards
2022-07-15 11:47:48 ERROR (MainThread) [custom_components.ui_lovelace_minimalist.load_plugins] HACS Frontend repo "lovelace-card-mod" is already installed, Remove it or disable include custom cards
2022-07-15 11:47:48 ERROR (MainThread) [custom_components.ui_lovelace_minimalist.load_plugins] HACS Frontend repo "lovelace-auto-entities" is already installed, Remove it or disable include custom cards
2022-07-15 11:47:48 ERROR (MainThread) [custom_components.ui_lovelace_minimalist.load_plugins] HACS Frontend repo "mini-graph-card" is already installed, Remove it or disable include custom cards
2022-07-15 11:47:48 ERROR (MainThread) [custom_components.ui_lovelace_minimalist.load_plugins] HACS Frontend repo "mini-media-player" is already installed, Remove it or disable include custom cards
2022-07-15 11:47:52 WARNING (MainThread) [homeassistant.config_entries] Config entry 'VMG8825-T50' for upnp integration not ready yet: Error connecting to device at location: http://192.168.1.1:38400/description.xml, err: ("ServerDisconnectedError('Server disconnected')", None); Retrying in background
2022-07-15 11:47:52 WARNING (zeroconf-ServiceBrowser-_googlecast._tcp-91) [pychromecast.dial] Failed to determine cast type for host <unknown> (<urlopen error [Errno 111] Connection refused>) (services:{ServiceInfo(type='mdns', data='Onkyo-TX-NR686-d5004ca68c4cada656918971bbec1d52._googlecast._tcp.local.')})
2022-07-15 11:47:52 ERROR (MainThread) [custom_components.hacs] HACS is disabled - HacsDisabledReason.INVALID_TOKEN
2022-07-15 11:47:52 ERROR (MainThread) [custom_components.hacs] Bad credentials
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 449, in async_can_update
    response = await self.async_github_api_method(self.githubapi.rate_limit)
  File "/config/custom_components/hacs/base.py", line 503, in async_github_api_method
    raise HacsException(_exception)
custom_components.hacs.exceptions.HacsException: Bad credentials
